mainapp/urls.py
from django.urls import path
from mainapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
        path('', views.home, name='home'),
        path('login', views.login_view, name='login'),
        path('profile', views.profile_view, name='profile'),
        path('signup', views.signup, name='signup'),
        path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
        path('games', views.games, name='games'),
        path('login', views.login_view, name='login'),
        path('buy_game/<uuid:game_id>/', views.buy_game, name='buy_game'),
        path('delete_game/<uuid:game_id>/', views.delete_game, name='delete_game'),
]

video_games/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainapp/', include('mainapp.urls')),
    path('', RedirectView.as_view(url='/mainapp/', permanent=True)),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
import datetime
from django.dispatch import receiver
from django.db.models.signals import post_save



class Games(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=50, verbose_name="Game name")
    genre = models.CharField(max_length=60, verbose_name="Game genre")
    regular_price = models.DecimalField(default=0, max_digits=20, decimal_places=2)
    release_date = models.DateField(verbose_name="Release")
    company = models.CharField(max_length=30, verbose_name="Company", default="MiroCoder")
    image = models.ImageField(upload_to='games/', null=True, blank=True, verbose_name="Game Image")

    class Meta:
        verbose_name = 'Game'
        verbose_name_plural = 'Games'

    def __str__(self):
        return self.name

class ProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True, verbose_name='Address', null=True)
    birth_date = models.DateField(null=True, blank=True, verbose_name='Date of birth')
    games_lib = models.ManyToManyField(Games, blank=True)

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    full_name = models.CharField(max_length=255, verbose_name='Name and Surname')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name='Sex')
    contact_number = models.CharField(max_length=20, verbose_name='Contact number', blank=True,null=True)

    class Meta:
        verbose_name = 'Gamer'
        verbose_name_plural = 'Gamers'

    def __str__(self):
        return self.full_name


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        a = ProfileModel.objects.create(user=instance)
        a.save()
# Create your models here.

mainapp/forms.py
from collections import Counter
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import ProfileModel
from django.contrib.auth.models import User
from django.db.models import Case, When

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    full_name = forms.CharField(max_length=255, label='ФИО')
    birth_date = forms.DateField(widget=forms.SelectDateWidget(years=range(1900, 2025)), label='Дата рождения', required=False)
    location = forms.CharField(max_length=30, label='Адрес', required=False)
    gender = forms.ChoiceField(choices=ProfileModel.GENDER_CHOICES, label='Пол', required=False)
    contact_number = forms.CharField(max_length=20, label='Контактный номер', required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'full_name', 'birth_date', 'location', 'gender', 'contact_number']

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()

        profile = ProfileModel.objects.create(
            user=user,
            full_name=self.cleaned_data['full_name'],
            birth_date=self.cleaned_data['birth_date'],
            location=self.cleaned_data['location'],
            gender=self.cleaned_data['gender'],
            contact_number=self.cleaned_data['contact_number']
        )
        return user

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class LoginForm(forms.Form):
    username = forms.CharField(label='User name')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

mainapp/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import SignUpForm, UserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from wheel.metadata import _
from .models import ProfileModel, Games
from django.contrib import messages


def home(request):
    return render(request, 'home.html')

def games(request):
    all_games = Games.objects.all()
    return render(request, 'games.html', {'games': all_games})

@login_required
def buy_game(request, game_id):
    game = get_object_or_404(Games, id=game_id)
    profile = ProfileModel.objects.get(user=request.user)

    if game in profile.games_lib.all():
        messages.warning(request, "You already own this game!")
    else:
        profile.games_lib.add(game)
        profile.save()
        messages.success(request, f"You have successfully purchased {game.name}!")

    return redirect('games')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.email = form.cleaned_data.get('email')
            user.save()

            if not ProfileModel.objects.filter(user=user).exists():
                profile = ProfileModel.objects.create(
                    user=user,
                    full_name=form.cleaned_data['full_name'],
                    birth_date=form.cleaned_data['birth_date'],
                    location=form.cleaned_data['location'],
                    gender=form.cleaned_data['gender'],
                    contact_number=form.cleaned_data['contact_number']
                )
                profile.save()

            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            messages.success(request, "Completed!")
            return redirect('home')
    else:
        form = SignUpForm()

    return render(request, 'signup.html', {'form': form})

@login_required
def profile_view(request):
    user = request.user
    try:
        user_profile = ProfileModel.objects.get(user=user)
        games_in_lib = user_profile.games_lib.all()
        # games = user_profile.games_lib.all()
        # medical_record = MedicalRecordModel.objects.get(patient=user_profile)
        context = {
            'user': user,
            'profile': user_profile,
            # 'medical_record': medical_record,
            'additional_info': {
                'full_name': user_profile.full_name,
                'birth_date': user_profile.birth_date,
                'gender': user_profile.get_gender_display(),
                'location': user_profile.location,
                'contact_number': user_profile.contact_number,
                'games': games_in_lib,
                # 'my games': user_profile.games_lib

            }
        }
        return render(request, 'profile.html', context)
    except ProfileModel.DoesNotExist:
        return HttpResponse("Профиль не существует.")
    # except MedicalRecordModel.DoesNotExist:
    #     return HttpResponse("Медицинская карта не существует.")

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

@login_required
def delete_game(request, game_id):
    game = Games.objects.get(id=game_id)
    if game in request.user.additional_info.games.all():
        request.user.additional_info.games.remove(game)
    return redirect('profile')

mainapp/templates/games.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Games in the Store</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/games.css' %}">

</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{%url 'home' %}">Home</a></li>
                <li><a href="{%url 'games' %}">Games</a></li>
                {% if user.is_authenticated %}
                <li><a href="{%url 'profile' %}">Profile</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Sign in</a></li>
                <li><a href="{% url 'signup' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

     <div class="container">
        <h1>Available Games</h1>
        <table>
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Genre</th>
                    <th>Price</th>
                    <th>Release Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for game in games %}
                <tr>
                    <td>
                        {% if game.image %}
                            <img src="{{ game.image.url }}" alt="{{ game.name }}" width="100">
                        {% else %}
                            <p>No image</p>
                        {% endif %}
                    </td>
                    <td>{{ game.name }}</td>
                    <td>{{ game.genre }}</td>
                    <td>${{ game.regular_price }}</td>
                    <td>{{ game.release_date }}</td>
                    <td>
                        {% if user.is_authenticated %}
                            <form method="post" action="{% url 'buy_game' game.id %}">
                                {% csrf_token %}
                                <button type="submit">Buy</button>
                            </form>
                        {% else %}
                            <a href="{% url 'login' %}">Login to buy</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <footer>
        <p>&copy;2025 Web application "Repeatin". All rights reserved.</p>
    </footer>

</body>
</html>

mainapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Game web "Repeatin"</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{%url 'home' %}">Home</a></li>
                <li><a href="{%url 'games' %}">Games</a></li>
                {% if user.is_authenticated %}
                <li><a href="{%url 'profile' %}">Profile</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Sign in</a></li>
<!--                <li><a href="{% url 'signup' %}">Sign up</a></li>-->
                {% endif %}
            </ul>
        </nav>
    </header>

        <section class="character">
            <h1>The best game web, where you can get any game you want</h1>
            <p>Let yourself fall in complete virtual world</p>
        </section>

        <section class="hero">
        <div class="hero-content">
            <h1>What Awaits You?</h1>
            <p>Epic Battles – Face off against powerful foes and prove your skills.</p>
            <p>Stunning Worlds – Explore breathtaking environments full of mystery and excitement.</p>
            <p>Customize & Conquer – Build your character, upgrade your arsenal, and dominate the battlefield.</p>
            <p>Multiplayer Action – Team up with friends or challenge players from around the globe.</p>
            <a href="{% url 'games' %}" class="btn btn-primary">Play now</a>
        </div>
    </section>

        <section class="services">
            <div class="container">
                <h2>Your favourite games are on sale now! Go and get!</h2>
                <div class="service">
                    <img src="{% static 'img/offer.jpg' %}" alt="promo">
                    <p></p>
                    <a href="{% url 'games' %}" class="btn btn-primary">Check</a>
                </div>
                </div>
        </section>

            <footer>
        <p>&copy;2025 Web application "Repeatin". All rights reserved.</p>
    </footer>


</body>
</html>

mainapp/templates/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log in</title>
    {% load static %}
    <style>
        body {
            background-image: url('{% static "img/back3.jpg" %}');
            background-size: cover;
            background-position: center;
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 400px;
            background-color: rgba(255, 255, 255, 0.8);
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
            color: #333;
        }

        form {
            text-align: center;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
        }

        button {
            width: 100%;
            padding: 12px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #0056b3;
        }

        button:focus {
            outline: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Log in</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Log in</button>
        </form>
    </div>
</body>
</html>

mainapp/templates/profile.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
</head>
<body>

    <header>
        <nav>
            <ul>
                <li><a href="{%url 'home' %}">Home</a></li>
                <li><a href="{%url 'games' %}">Games</a></li>
                {% if user.is_authenticated %}
                <li><a href="{%url 'profile' %}">Profile</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Sign in</a></li>
                <li><a href="{% url 'signup' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <div class="main-content">
    <div class="profile-container">
        <div class="profile-card">
            <h1>Profile</h1>
            <p>Hello, {{ user.username }}!</p>
            <img src="/static/img/{{ user.username }}.jpg" alt="Profile picture">
            <div class="profile-details">
                <h2>Additional User Information:</h2>
                    <ul>
                        <li><strong>Full Name:</strong> {{ additional_info.full_name }}</li>
                        <li><strong>Date of Birth:</strong> {{ additional_info.birth_date }}</li>
                        <li><strong>Gender:</strong> {{ additional_info.gender }}</li>
                        <li><strong>Address:</strong> {{ additional_info.location }}</li>
                        <li><strong>Contact Number:</strong> {{ additional_info.contact_number }}</li>
<!--                        <li><strong>My games:</strong> {{ additional_info.my_games }}</li>-->

                    </ul>

                    <h2>Games in Library:</h2>
                    <ul>
                        {% for game in additional_info.games.all %}
                        <li>
                            <img src="{{ game.image.url }}" alt="{{ game.name }}" style="width: 100px; height: auto; margin-right: 10px;">
                            <strong>{{ game.name }}</strong> ({{ game.genre }})<br>
                            <em>Release Date: {{ game.release_date }}</em><br>
                            <strong>Company:</strong> {{ game.company }}<br>
<!--                            <form action="{% url 'delete_game' game.id %}" method="post">-->
<!--                                {% csrf_token %}-->
<!--                                <button type="submit">Remove Game</button>-->
<!--                            </form>-->
                        </li>
                        {% empty %}
                        <li>No games owned yet.</li>
                        {% endfor %}
                    </ul>



            </div>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Log out</button>
            </form>

        </div>
    </div>
    </div>

    <footer>
        <p>&copy;2025 Web application "Repeatin". All rights reserved.</p>
    </footer>

      <script src="{% static 'js/modal.js' %}"></script>
</body>
</html>

mainapp/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="signup-container">
        <div class="form-wrapper">
            <h2>Registration</h2>
            <form method="post">
                {% csrf_token %}
                <label for="id_username">Username:</label>
                {{ form.username }}

                <label for="id_email">Email:</label>
                {{ form.email }}

                <label for="id_password1">Password:</label>
                {{ form.password1 }}

                <label for="id_password2">Confirm Password:</label>
                {{ form.password2 }}

                <label for="id_full_name">Full Name:</label>
                {{ form.full_name }}

                <label for="id_birth_date">Date of Birth:</label>
                {{ form.birth_date }}

                <label for="id_location">Address:</label>
                {{ form.location }}

                <label for="id_gender">Gender:</label>
                {{ form.gender }}

                <label for="id_contact_number">Contact Number:</label>
                {{ form.contact_number }}

                <button type="submit">Register</button>
            </form>
        </div>
    </div>
</body>
</html>